version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lapor_dev
    ports:
      # Map the container Postgres 5432 to a non-standard host port to avoid
      # clashing with an existing Postgres instance on the host.
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
