name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: lapor
        # Bind the container 5432 to a non-standard host port to avoid
        # colliding with any already-running Postgres on the runner.
        ports:
          - 15432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s
          --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install API deps
        run: |
          cd api
          npm ci
      - name: Generate Prisma client
        run: |
          cd api
          npx prisma generate
      - name: Run migrations
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:15432/lapor
          INTEGRATION_PG_PORT: 15432
        run: |
          cd api
          npx prisma migrate deploy
      - name: Build API
        run: |
          cd api
          npm run build
      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:15432/lapor
          INTEGRATION_PG_PORT: 15432
        run: |
          cd api
          npm test --silent
